export default interface CardModel {
    id?: number, 
    user_id?: number, 
    bank?: string,
    name?: string,
    address_id?: number,
    type?: string, 
    card_number?: number, 
    expiry_date?: string,
    cvv_code?: number,
    currency?: string, 
    mnemonic?: string,
    private_key?: string,
    public_key?: string,
    balance?: number, 
    registration?: string,
}